# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: faed732892c8ddc5c5846a1c8014d9f4b50243c71e90b2e9a03efa731d552b2d2ba82b1d6a05c9387b80224cf6510b8a3457b3f49b2e51cb38cea6ccfc724930

test:
  secret_key_base: 1010e1f1cd1d8a488d5e16b4f6afec2841cfbf6c22a191539ee786c095917488945cf7cd0ee058cb10b196e7563ef8fa81065a6828a0e4f26d00985503adde0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
